import{a as B,S as v,i as l}from"./assets/vendor-CvMZEKsE.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const P="50483105-27f5d2c3ecd49e5e7204371e4",I="https://pixabay.com/api/",M=20;async function d(s,o=1){const t={key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:M,page:o};return(await B.get(I,{params:t})).data}let $=new v("#gallery a");const u=document.getElementById("gallery"),f=document.getElementById("loader"),m=document.getElementById("load-more");function p(s){const o=s.map(({webformatURL:t,largeImageURL:n,tags:e,likes:r,views:a,comments:E,downloads:w})=>`
        <li class="gallery-item">
          <a href="${n}">
            <img src="${t}" alt="${e}" />
              </a>
              <div class="gallery-info">
        <p><b>Likes:</b> <span>${r}</span></p>
        <p><b>Views:</b> <span>${a}</span></p>
        <p><b>Comments:</b> <span>${E}</span></p>
        <p><b>Downloads:</b> <span>${w}</span></p>
      </div>
    </li>`).join("");u.insertAdjacentHTML("beforeend",o),$.refresh()}function O(){u.innerHTML=""}function y(){f.classList.add("show")}function g(){f.classList.remove("show")}function h(){m.style.display="block"}function b(){m.style.display="none"}let i=1,c="",L=0;const q=document.getElementById("search-form"),A=document.getElementById("load-more");q.addEventListener("submit",async s=>{s.preventDefault();const o=s.target.elements.query.value.trim();if(o){c=o,i=1,O(),b(),y();try{const t=await d(c,i);if(L=t.totalHits,t.hits.length===0){l.info({message:"No images found. Try another search."});return}p(t.hits),t.totalHits>15&&h()}catch{l.error({message:"Fetch error."})}finally{g()}}});A.addEventListener("click",async()=>{i+=1,y(),b();try{const s=await d(c,i);p(s.hits);const{height:o}=document.querySelector("#gallery a").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"});const t=Math.ceil(L/15);i<t?h():l.info({message:"We're sorry, but you've reached the end of search results."})}catch{l.error({message:"Error loading more images."})}finally{g()}});
//# sourceMappingURL=index.js.map
