import{a as B,S as v,i as l}from"./assets/vendor-CvMZEKsE.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const P="50483105-27f5d2c3ecd49e5e7204371e4",I="https://pixabay.com/api/",M=20;async function u(s,o=1){const t={key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:M,page:o};return(await B.get(I,{params:t})).data}let $=new v("#gallery a");const f=document.getElementById("gallery"),m=document.getElementById("loader"),p=document.getElementById("load-more");function y(s){const o=s.map(({webformatURL:t,largeImageURL:n,tags:e,likes:r,views:a,comments:E,downloads:w})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${t}" alt="${e}" />
        </a>
        <div class="gallery-info">
          <p><b>Likes:</b> <span>${r}</span></p>
          <p><b>Views:</b> <span>${a}</span></p>
          <p><b>Comments:</b> <span>${E}</span></p>
          <p><b>Downloads:</b> <span>${w}</span></p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",o),$.refresh()}function O(){f.innerHTML=""}function g(){m.classList.add("show")}function h(){m.classList.remove("show")}function b(){p.style.display="block"}function c(){p.style.display="none"}let i=1,d="",L=0;const q=document.getElementById("search-form"),A=document.getElementById("load-more");c();q.addEventListener("submit",async s=>{s.preventDefault();const o=s.target.elements.query.value.trim();if(o){d=o,i=1,O(),c(),g();try{const t=await u(d,i);if(L=t.totalHits,t.hits.length===0){l.info({message:"No images found. Try another search."});return}y(t.hits),t.totalHits>15&&b()}catch{l.error({message:"Fetch error."})}finally{h()}}});A.addEventListener("click",async()=>{i+=1,g(),c();try{const s=await u(d,i);y(s.hits);const{height:o}=document.querySelector("#gallery a").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"});const t=Math.ceil(L/15);i<t?b():l.info({message:"We're sorry, but you've reached the end of search results."})}catch{l.error({message:"Error loading more images."})}finally{h()}});c();
//# sourceMappingURL=index.js.map
